[features]
seeds = false
skip-lint = false
[programs.devnet]
myepicproject = "HETREq43H1Akx78abqB26XeyGobuzDCKyYvio3Y6MXxH"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/chad/.config/solana/devnet.json"

[scripts]
test = "yarn run mocha -t 1000000 tests/"
